### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by daviddias** [pgte/ipfs-iiif-db#1]
@pgte if I understood correctly, this module is ready to be tested. Could you provide an example for @edsilv and @aeschylus that demonstrates:

- How to bundle it using browserify
- Operations to sync state between two nodes

**Comment by pgte** [comment]
@diasdavid still working on finding out the reason for the latency I'm observing..

**Comment by daviddias** [comment]
Understood. I wonder if that only happens in certain network configs (if it is the router causing the delay).

That being said, having something that both viewers can use, even with a delay, is valuable so that the work can happen in parallel.

**Comment by pgte** [comment]
@edsilv @aeschylus @diasdavid :
I've created [an example](https://github.com/pgte/ipfs-iiif-db/tree/master/examples/simple-producer-consumer) that has [a quick video demo](https://www.youtube.com/watch?v=hscU-Mg242M).

I'm browserifying [this app file](https://github.com/pgte/ipfs-iiif-db/blob/master/examples/simple-producer-consumer/src/app.js) using [this command](https://github.com/pgte/ipfs-iiif-db/blob/master/examples/simple-producer-consumer/package.json#L5).

Also, the API is documented [here](https://github.com/pgte/ipfs-iiif-db#readme), but may change (mostly based on your feedback, I guess).

Ping me if you have any question, and feedback is welcome! 😄
