### ISSUE TITLE
browser.min.js has dependency on y-leveldb.es6

### ISSUE THREAD

**Issue by mitra42** [pgte/ipfs-iiif-db#9]
If I include:
<script src="https://unpkg.com/ipfs-iiif-db/dist/browser.min.js">
The browser tries to y-leveldb.es6, from the server containing this line. (i.e. not from unpkg.com) 
Obviously y-leveldb.es6 isn't on the server so it fails. 
<p>
The "browser.js" version has the same problem,

**Comment by mitra42** [comment]
I note that "y-leveldb" doesn't appear in browser.js, so I'm not sure where to look for a fix.

**Comment by pgte** [comment]
That's weird. I've (re)checked the bundle and it contains no reference to the y-leveldb package, even though I suspect it is Y.js that is trying to fetch that directly..

Some questions:

What version of ipfs-iiif-db are you getting? Could you try pointing to the latest (https://unpkg.com/ipfs-iiif-db@2.4.0/dist/browser.min.js) and see if this still happens?

Are you passing any options to the constructor?

Is there any live page where I can look at this?

**Comment by mitra42** [comment]
Thanks .. that was partly what confused me, I couldnt find y-leveldb in browser.js either. 

I switched to your suggested version - same effect (comments below refer to running on that).

The actual address being loaded is: http://localhost:63343/bower_components/y-leveldb/y-leveldb.es6
The call Stack is (as reported by Firefox) is ...

- requestModules:  https://unpkg.com/ipfs-iiif-db@2.4.0/dist/browser.min.js:62:27336
- 	Y/</< https://unpkg.com/ipfs-iiif-db@2.4.0/dist/browser.min.js:62:28758


I'm noot sure how to interpret these call stacks inside such minified code, but looks to me like its trying to load modules in order to start Y ? 

Options to IIIF are: { ipfs: defaultipfsoptions, store: "leveldb", partition: "dweb20170612" }
Which I'm presuming is where the loading of leveldb is triggered.  The IPFS options are as shown below, and are based on options pulled out of the IIIF examples.

defaultipfsoptions = {
    repo: '/tmp/ipfs_dweb20170612',
    config: {
        Addresses: { Swarm: [ '/libp2p-webrtc-star/dns4/star-signal.cloud.ipfs.team/wss' ] },   // For IIIF - same as defaults
        Discovery: { webRTCStar: { Enabled: true } }    // For IIIF - same as defaults
    },
    EXPERIMENTAL: {
        pubsub: true
    }
};

Note that all of this works in the node.js environment where I was testing it. Only changes were to use a typical browser.js file to set global variables from "requires" and then pulling the IIIF out of that require and loading from the HTML directly because of Issue #8

**Comment by mitra42** [comment]
Also ... sorry, no live page yet, I could send files, but the call to do this is buried fairly deep.

**Comment by pgte** [comment]
The problem is with the options.
Leveldb is not supported in the browser..

**Comment by daviddias** [comment]
@mitra42 see documentation on the README -- https://github.com/ipfs-shipyard/ipfs-iiif-db#instantiate --, you just have to change it to `indexeddb`.

![image](https://user-images.githubusercontent.com/1211152/28241248-c69701f2-6988-11e7-8993-0570fbcb6ed7.png)

Also, it might be useful to you to check out two other tutorials that got recorded in video, see:
- https://www.youtube.com/watch?v=Nv_Teb--1zg
- https://www.youtube.com/watch?v=-kdx8rJd8rQ

**Comment by mitra42** [comment]
Thanks. 
Do I presume that for a different project (not IIIF) we should invent our own partition or does that pollute some namespace ?

**Comment by pgte** [comment]
@mitra42 yes, agree, that would be a good practise.

**Comment by mitra42** [comment]
Also .. what is the cost on the network of the partitions ? If there were 100's or 1000's of pubsub "feeds" would these be better (from impacting the network) as separate partitions or a single partition that is filtered at the client level?

**Comment by pgte** [comment]
If you make wise use of partitioning you should see less messages.

**Comment by mitra42** [comment]
That wasn't quite my point .... here's how we are using it.  Many resources in our thinking are "lists", typically once something is listed we monitor for other things added to the list as long as the browser window is open.  Each page could have many "lists", if I partition it down to that level it would create a lot of partitions, and I want to make sure that doing so doesn't hurt the network overall (not just us) given how fragile everything seems.

**Comment by pgte** [comment]
@mitra42 the partition count on a given node scales well under a certain number, mainly because subscriptions are not persisted. If you keep it below the thousands you should have no problem.

**Comment by mitra42** [comment]
OK - we've moved to using YJS directly (so that we can open multiple subscriptions at same time) and fine-grained it so each list is its own "room" in Y terms (which I think corresponds to a partition in IIIF
